name: Remove Code

on:
  workflow_dispatch:
    inputs:
      reward_id:
        description: 'ID of the reward'
        required: true
        type: integer

jobs:
  remove-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Remove code
      id: remove_code
      run: |
        reward_id=${{ github.event.inputs.reward_id }}
        codes_file="private/codes.json"

        # Esegui la rimozione del codice con jq
        jq --argjson reward_id "$reward_id" '
        .codes |= map(
          if .reward_id == $reward_id then
            .codes |= .[1:]
          else
            .
          end
        )' "$codes_file" > "$codes_file.tmp"

        mv "$codes_file.tmp" "$codes_file"

        # Controlla se l'eliminazione è avvenuta con successo
        assigned_code=$(jq -r --argjson reward_id "$reward_id" '
        .codes[] | select(.reward_id == $reward_id) | .codes[0]' "$codes_file")

        if [ -z "$assigned_code" ]; then
          echo "DELETION_SUCCESS=true" >> $GITHUB_ENV
        else
          echo "DELETION_SUCCESS=false" >> $GITHUB_ENV
        fi

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit changes
      if: env.DELETION_SUCCESS == 'true'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add private/codes.json
        git commit -m "Update codes for reward ID ${{ github.event.inputs.reward_id }}"
        git push
